#!/bin/bash

#
# Pre build hook for Docker Automated Build.
#

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

cp -r ../../../supervisely_lib .

echo "pre_build hook terminated successfully."
